#!/usr/bin/python3

# Generate klib.h, which contains addresses for kernel trampoline
# functions
# Note that you separately have to add a function to u_common.h to create
# a C API for it.

def main():
    print("// generated by gen_klib_header.py; do not edit")
    print()

    with open("kernel/memlayout.h") as f:
        for line in f:
            if line.startswith("#define F_"):
                print(line.strip())

if __name__ == "__main__":
    main()
